### ISSUE TITLE
Installation steps are outdated after the backstage composability work. 

### ISSUE THREAD

**Issue by schopparapu9** [RoadieHQ/backstage-plugin-datadog#24]
Hi folks, 

Steps mentioned in this [page](https://github.com/RoadieHQ/backstage-plugin-datadog) are not working anymore. Running into compile errors when trying to build the project. Seems like this is an issue later the [composability](https://backstage.io/docs/plugins/composability) work. Please help. 

Thanks.

**Comment by Irma12** [comment]
@schopparapu9 Thank you for reporting this. We have updated the README file 🎉

**Comment by Irma12** [comment]
@Irma12 Thank you for your patience. We have been able to reproduce the issue and applied the fix in v1.1.4. It should work smooth now.

**Comment by Irma12** [comment]
@schopparapu9 If you added annotation to already registered component you probably need to unregister and re-add it again so changes take effect.
