### ISSUE TITLE
Installation step 4 no longer works with version 0.2.1

### ISSUE THREAD

**Issue by wrighbr** [RoadieHQ/backstage-plugin-datadog#6]
Hey Guys 

thanks for the project but I was just wondering if you could update the installation steps for version 0.2.1 as there only work for version 0.1.1

looks like a couple thing have been deprecated in the last version.

cheers

**Comment by padraigobrien** [comment]
Hi @wrighbr  , i will take a look at this and get back to you

**Comment by andrewthauer** [comment]
Yep, the instructions are out of date. The `annotation` key is no longer correct + there are references to `argo-cd` as well which seems to be a copy pasta 🍝 🐱 . I also created #9 which suggests possibly another rename of the annotation prefix.

**Comment by padraigobrien** [comment]
Hi @wrighbr , I am closing this. I updated this plugin and tested it on a new instance of backstage
