### ISSUE TITLE
Dashboard with mutliple charts fails to load

### ISSUE THREAD

**Issue by andrewthauer** [RoadieHQ/backstage-plugin-datadog#8]
## Expected Behavior

You can view a dashboard url with multiple charts/widgets.

## Current Behavior

Trying to view a dashboard with multiple widgets doesn't see to work and results in a datadog Oof error. It seems to be related to the appending of the `tvmode` query string. Removing it seems to avoid the error.

## Possible Solution

I'm not sure what `tvmode` does, but is it necessary?

## Steps to Reproduce

1. Create a Datadog dashboard with 5-6 charts
2. Configure the dashboard for sharing
3. Use the shared dashboard url on the datadog entity annotation
4. Try and view the dashboard

## Context

Testing out the datadog plugin:

## Your Environment

- Plugin Version: 0.2.1
- Backstage version: Up to date
- NodeJS Version: 14
- Operating System and Version: macOS
- Browser Information: chrome or ff

**Comment by padraigobrien** [comment]
Hi @andrewthauer, I removed the tv_mode as it was causing the dashboard to fail, as you suspected. I will close this issue. Let me know on discord or log a new issue if there are any further problems or need further help.
