### ISSUE TITLE
The datadog annotations should be prefixed with datadoghq.com

### ISSUE THREAD

**Issue by andrewthauer** [RoadieHQ/backstage-plugin-datadog#9]
## Expected Behavior

As per common backstage conventions for annotations, the left side of annotation typically matches the domain name of the company or organization (e.g. `github.com`, `backstage.io`, `jenkins.io`, etc.)

## Current Behavior

The annotation for the plugin uses the prefix `datadog/dashboard-url` which doesn't map to a domain name of https://www.datadoghq.com/.

## Possible Solution

Rename the annotation prefix to match `datadoghq.com` or `datadog.com` (which seems to redirect to the prior). For example `datadoghq.com/dashboard-url`

## Steps to Reproduce

n/a

**Comment by padraigobrien** [comment]
Hi, @andrewthauer. I have updated this repo, so we use datadoghq.com in the annotations. I will close this issue. Let me know on discord or log a new issue if there are any further problems or need further help.
